// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3ied5W5CoZR9X0pu5CTgyTttnu6_pgA0',
    appId: '1:840521403888:web:bac9f9915a76e79b2ea135',
    messagingSenderId: '840521403888',
    projectId: 'waqas-123456',
    authDomain: 'waqas-123456.firebaseapp.com',
    storageBucket: 'waqas-123456.appspot.com',
    measurementId: 'G-ZY05K26EK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQXboZYc2bj2BGY9ECH-1haR3aW42roa8',
    appId: '1:840521403888:android:727cd5baa33f2e112ea135',
    messagingSenderId: '840521403888',
    projectId: 'waqas-123456',
    storageBucket: 'waqas-123456.appspot.com',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeDA0I8-VEQ506nsPYRjN3Bb4vhB7lD38',
    appId: '1:840521403888:ios:37db4dff189f630e2ea135',
    messagingSenderId: '840521403888',
    projectId: 'waqas-123456',
    storageBucket: 'waqas-123456.appspot.com',
    androidClientId:
        '840521403888-i190str6b2kl0rdetq4skukpn594u2vi.apps.googleusercontent.com',
    iosClientId:
        '840521403888-li601360s78rinvhki7unukc4te8slu0.apps.googleusercontent.com',
    iosBundleId: 'com.waqas.tailorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3ied5W5CoZR9X0pu5CTgyTttnu6_pgA0',
    appId: '1:840521403888:web:5d1d6a5c56b988a52ea135',
    messagingSenderId: '840521403888',
    projectId: 'waqas-123456',
    authDomain: 'waqas-123456.firebaseapp.com',
    storageBucket: 'waqas-123456.appspot.com',
    measurementId: 'G-RJE7NMP9YN',
  );
}
